[project]
name = "mlflow-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lenny Ng'ang'a", email = "codewithlennylen254@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mlflow>=3.16.1",
]

[project.scripts]
mlflow-quickstart = "mlflow_quickstart:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
